authapp/urls.py
"""
authapp/urls.py
"""
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.user_login, name='login'),
    re_path(r'^logout/$', authapp.user_logout, name='logout'),
    re_path(r'^register/$', authapp.user_register, name='register'),
    re_path(r'^update/$', authapp.user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

mainapp/urls.py
"""
mainapp/urls.py
"""
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),
    re_path(r'^news/(\d+)/$', mainapp.site, name='site'),

    re_path(r'^topics/$', mainapp.TopicsListView.as_view(), name='topics'),
    re_path(r'^topic/create/$', mainapp.TopicCreateView.as_view(), name='topic_create'),
    re_path(r'^topic/update/(?P<pk>\d+)/$', mainapp.TopicUpdateView.as_view(), name='topic_update'),
    re_path(r'^topic/delete/(?P<pk>\d+)/$', mainapp.TopicDeleteView.as_view(), name='topic_delete'),

    re_path(r'^topic_sites/(?P<pk>\d+)/$', mainapp.TopicSitesListView.as_view(), name='topic_sites'),
    re_path(r'^topic_site/create/(?P<pk>\d+)/$', mainapp.TopicSiteCreateView.as_view(), name='topicsite_create'),
    re_path(r'^topic_site/delete/(?P<pk>\d+)/$', mainapp.TopicSiteDeleteView.as_view(), name='topicsite_delete'),

]

news_parser/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import re_path, include

# import mainapp

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^admin/', admin.site.urls),  # типовая админка
    # re_path(r'^news/', include('mainapp.urls', namespace='news')),
    # re_path(r'^topics/', include('mainapp.urls', namespace='topics')),
    # re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    # re_path(r'^auth/verify/google/oauth2/', include('social_django.urls', namespace='social')),
]
# re_path(r'^(\d+)/$', mainapp.site, name='site'),

authapp/models.py
"""
authapp/models.py
"""
from datetime import timedelta
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now


def get_now():
    """
    Возвращает текущую дату плюс два дня.
    :return: date
    """
    return now() + timedelta(hours=48)


class SiteUser(AbstractUser):
    """
    Класс SiteUser
    """
    age = models.PositiveIntegerField(verbose_name='Age', null=True)
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=get_now())

    def is_activation_key_expired(self):
        return now() > self.activation_key_expires

authapp/forms.py
"""
authapp/forms.py
"""
import random
import hashlib
import django.forms as forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import SiteUser


class SiteUserLoginForm(AuthenticationForm):
    """
    Класс SiteUserLoginForm
    """

    class Meta:
        """
        Класс Meta
        """
        model = SiteUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # вызов метода родительского класса
        for field_name, field in self.fields.items():
            # добавляем всем элементам класс с таким именем
            field.widget.attrs['class'] = 'form-control'


class SiteUserRegisterForm(UserCreationForm):
    """
    Класс SiteUserRegisterForm
    """

    class Meta:
        """
        Класс Meta
        """
        model = SiteUser
        fields = (
            'username',
            'first_name',
            'password1',
            'password2',
            'email',
            'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        """
        Автоматически вызывается метод clean, когда выодятся неверные данные (для каждого поля)
        :return: data
        """
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

    def save(self):
        user = super().save()
        user.is_active = False
        # salt - модификатор
        salt = hashlib.sha1(
            str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1(
            (user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class SiteUserChangeForm(UserChangeForm):
    """
    Класс SiteUserChangeForm
    """

    class Meta:
        """
        Класс Meta
        """
        model = SiteUser
        fields = (
            'username',
            'first_name',
            'last_name',
            'password',
            'email',
            'age',
            'is_staff')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':  # спрятать поле с паролем
                field.widget = forms.HiddenInput()

    def clean_age(self):
        """
        Автоматически вызывается метод clean, когда выодятся неверные данные (для каждого поля)
        :return: data
        """
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

authapp/views.py
"""
authapp/views.py
"""
from django.shortcuts import render, HttpResponseRedirect
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail

from authapp.models import SiteUser
from authapp.forms import SiteUserLoginForm, SiteUserRegisterForm, SiteUserChangeForm


def user_login(request):
    """
    User Login
    :param request:
    :return: render
    """
    next_param = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST':
        form = SiteUserLoginForm(data=request.POST)
        if form.is_valid():
            print('форма заполнена корректно')
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                print('залогинились')
                # if 'next' in request.POST.keys():
                if 'next' in request.POST.keys() and request.POST['next']:
                    return HttpResponseRedirect(request.POST['next'])

                return HttpResponseRedirect(reverse('main:index'))

    else:
        form = SiteUserLoginForm()

    context = {
        'form': form,
        'next': next_param,
    }
    return render(request, 'authapp/login.html', context)


def user_logout(request):
    """
    User Logout
    :param request:
    :return: HttpResponseRedirect
    """
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def user_register(request):
    """
    User Register
    :param request:
    :return: render
    """
    if request.method == 'POST':
        form = SiteUserRegisterForm(request.POST, request.FILES)
        # ВАЖНО указать request.FILES - данные для загрузки на сервер,
        # А на форме должно быть указано свойство enctype="multipart/form-data"
        if form.is_valid():
            user = form.save()
            if send_verify_mail(user):
                print('сообщение подтверждения отправлено')
                return HttpResponseRedirect(reverse('main:index'))

            print('ошибка отправки сообщения')
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = SiteUserRegisterForm()

    context = {
        'form': form,
        'title': 'регистрация',
    }
    return render(request, 'authapp/register.html', context)


def user_update(request):
    """
    User Update
    :param request:
    :return: render
    """
    if request.method == 'POST':
        edit_form = SiteUserChangeForm(
            request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        edit_form = SiteUserChangeForm(instance=request.user)

    content = {
        'title': 'редактирование',
        'edit_form': edit_form,
    }

    return render(request, 'authapp/edit.html', content)


def send_verify_mail(user):
    """
    Verify Mail
    :param user:
    :return: send_mail()
    """
    verify_link = reverse(
        'auth:verify', args=[
            user.email, user.activation_key])

    title = f'Подтверждение учетной записи {user.username}'

    message = f'Для подтверждения учетной записи {user.username} ' \
              f'на портале {settings.DOMAIN_NAME} ' \
              f'перейдите по ссылке: \n{settings.DOMAIN_NAME}{verify_link}'

    return send_mail(
        title, message, settings.EMAIL_HOST_USER, [
            user.email], fail_silently=False)


def verify(request, email, activation_key):
    """
    Verify activation key
    :param request:
    :param email:
    :param activation_key:
    :return: render or HttpResponseRedirect
    """
    try:
        user = SiteUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            login(
                request,
                user,
                backend='django.contrib.auth.backends.ModelBackend')
        else:
            print(f'error activation user: {user}')
        return render(request, 'authapp/verification.html')
    except Exception as err:
        print(f'error activation user: {err} -> {err.args}')
        return HttpResponseRedirect(reverse('main:index'))

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link rel="icon" type="image/gif" href="{% static 'img/cool.gif' %}" />
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Login
            </div>            
            
            {% block content %}
            {% endblock %}
        </div>
	</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="Save">
    </form>
    <a href="{% url 'main:index' %}" class="btn btn-round form-control last">
        Home
    </a>
 {% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Login">
    </form>
    <a href="{% url 'auth:register' %}" class="btn btn-round form-control">
        Registration
    </a>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Register">
    </form>

{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    {% if user %}
        <h3>Congratulation!</h3>
        <br>
        <h4>User {{user.username}} was confirmed.</h4>
    {% else %}
        <h3>Verification failed.</h3>
    {% endif %}
    <br>
    <button class="btn btn-round form-control">
        <a href="{% url 'main:index' %}" class="">
            Home
        </a>
    </button>

{% endblock %}