authapp/urls.py
"""
authapp/urls.py
"""
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.user_login, name='login'),
    re_path(r'^logout/$', authapp.user_logout, name='logout'),
    re_path(r'^register/$', authapp.user_register, name='register'),
    re_path(r'^update/$', authapp.user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

mainapp/urls.py
"""
mainapp/urls.py
"""
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),
    re_path(r'^news/(\d+)/$', mainapp.site, name='site'),

    re_path(r'^topics/$', mainapp.TopicsListView.as_view(), name='topics'),
    re_path(r'^topic/create/$', mainapp.TopicCreateView.as_view(), name='topic_create'),
    re_path(r'^topic/update/(?P<pk>\d+)/$', mainapp.TopicUpdateView.as_view(), name='topic_update'),
    re_path(r'^topic/delete/(?P<pk>\d+)/$', mainapp.TopicDeleteView.as_view(), name='topic_delete'),

    re_path(r'^topic_sites/(?P<pk>\d+)/$', mainapp.TopicSitesListView.as_view(), name='topic_sites'),
    re_path(r'^topic_site/create/(?P<pk>\d+)/$', mainapp.TopicSiteCreateView.as_view(), name='topicsite_create'),
    re_path(r'^topic_site/delete/(?P<pk>\d+)/$', mainapp.TopicSiteDeleteView.as_view(), name='topicsite_delete'),

]

news_parser/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import re_path, include

# import mainapp

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^admin/', admin.site.urls),  # типовая админка
    # re_path(r'^news/', include('mainapp.urls', namespace='news')),
    # re_path(r'^topics/', include('mainapp.urls', namespace='topics')),
    # re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    # re_path(r'^auth/verify/google/oauth2/', include('social_django.urls', namespace='social')),
]
# re_path(r'^(\d+)/$', mainapp.site, name='site'),

mainapp/models.py
"""
mainapp/models.py
"""
from django.db import models
from authapp.models import SiteUser


class Site(models.Model):
    """
    Список сайтов, которые можем обрабатывать.
    """
    name = models.CharField(
        max_length=200,
        verbose_name='Name',
        null=False,
        unique=True)
    ref = models.CharField(
        max_length=1024,
        verbose_name='Reference',
        null=False)
    descr = models.CharField(
        max_length=1024,
        verbose_name='Description',
        null=True)

    def __str__(self):
        return f'{self.name}'


class Topic(models.Model):
    """
    Список новостных тем, которые настраивает пользователь
    """
    user = models.ForeignKey(
        SiteUser,
        verbose_name='User',
        on_delete=models.CASCADE)

    name = models.CharField(max_length=200, verbose_name='Topic Name')
    keywords = models.CharField(
        max_length=1024,
        verbose_name='Keywords, phrases')
    inactive = models.BooleanField(verbose_name='Inactive')
    period_start = models.DateTimeField(
        blank=True, null=True, verbose_name='Active Period Start')
    period_end = models.DateTimeField(
        blank=True, null=True, verbose_name='Active Period End')

    def __str__(self):
        return f'{self.name}'


class News(models.Model):
    """
    Общая лента всех новостей
    """
    site = models.ForeignKey(
        Site,
        verbose_name='Site',
        on_delete=models.CASCADE,
        null=True)

    news_date = models.DateTimeField(blank=True, verbose_name='News date')
    ref = models.CharField(
        max_length=1024,
        blank=False,
        verbose_name='Reference')
    brief_info = models.TextField(blank=True, verbose_name='News (brief)')
    info = models.TextField(
        blank=True,
        verbose_name='News (words)',
        default='')
    raw_info = models.TextField(
        blank=True,
        verbose_name='News (raw)',
        default='')
    raw_converted = models.BooleanField(
        verbose_name='Raw converted', default=False)


class TopicSite(models.Model):
    """
    Сайты, подлежащие обработке для топика
    """
    topic = models.ForeignKey(
        Topic,
        verbose_name='Topic',
        on_delete=models.CASCADE)
    site = models.ForeignKey(
        Site,
        verbose_name='Site',
        on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.site.name}'


class TopicNews(models.Model):
    """
    Новости, отобранные по топику
    """
    topic = models.ForeignKey(
        Topic,
        verbose_name='Topic',
        on_delete=models.CASCADE)
    news = models.ForeignKey(
        News,
        verbose_name='News',
        on_delete=models.CASCADE)
    news_date = models.DateTimeField(
        blank=True, verbose_name='News date', null=True)
    is_send = models.BooleanField(verbose_name='Is send?', default=False)
    send_date = models.DateTimeField(
        blank=True, verbose_name='Send date', null=True)

mainapp/forms.py
"""
mainapp/forms.py
"""
import django.forms as forms
from mainapp.models import Topic, TopicSite


class TopicEditForm(forms.ModelForm):
    class Meta:
        model = Topic
        # fields = '__all__'
        exclude = ('user',)  # Чтобы вывести поле discount

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # field.help_text = ''


class TopicSiteEditForm(forms.ModelForm):
    class Meta:
        model = TopicSite
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

mainapp/views.py
"""
mainapp/views.py
"""
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test

from mainapp.models import Site, News, Topic, TopicSite
from mainapp.forms import TopicEditForm, TopicSiteEditForm


def index(request):
    """
    Основная страница
    :param request:
    :return: render
    """
    sites = Site.objects.all()

    context = {
        'page_title': 'Financial News Parser',
        'sites': sites,
    }
    return render(request, 'mainapp/index.html', context)


def site(request, pkey=None):
    """
    Отображение новостей выбранного финансового сайта
    :param request:
    :param pkey:
    :return: render
    """
    if pkey is None:
        index(request)

    news = News.objects.filter(site__pk=pkey).order_by('-news_date')[:20]
    current_site = Site.objects.get(pk=pkey)
    site_name = current_site.name if current_site else ''
    context = {
        'page_title': 'Financial News Parser',
        'news': news,
        'site_name': site_name,
    }
    return render(request, 'mainapp/news.html', context)


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicsListView(ListView):
    """
    Вывод списка топиков
    """
    model = Topic
    template_name = 'mainapp/topic_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'FNP: Список топиков'
        return context

    def get_ordering(self):
        return ['name']

    def get_queryset(self):
        return self.request.user.topic_set.all()


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicCreateView(CreateView):
    """
    Добавление топика
    """
    model = Topic
    form_class = TopicEditForm
    # template_name = 'mainapp/topic_update.html'
    success_url = reverse_lazy('main:topics')

    # fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'FNP: Новый топик'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicUpdateView(UpdateView):
    model = Topic
    success_url = reverse_lazy('main:topics')
    form_class = TopicEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'FNP: Изменение топика'
        return context


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicDeleteView(DeleteView):
    model = Topic
    success_url = reverse_lazy('main:topics')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'FNP: Удаление топика'
        return context


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicSitesListView(ListView):
    model = TopicSite
    topic = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # print('CONTEXT==', self.category)
        context['page_title'] = 'FNP: Сайты топика'
        context['topic'] = get_object_or_404(Topic, pk=self.topic)
        return context

    def get_ordering(self):
        return ['name']

    def get_queryset(self):
        # print('KWARGS=', self.kwargs['pk'])
        self.topic = self.kwargs['pk']
        return TopicSite.objects.filter(topic__pk=self.topic)


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicSiteCreateView(CreateView):
    model = TopicSite
    topic = None
    # success_url = reverse_lazy('admin:products')
    form_class = TopicSiteEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'FNP: Новый сайт топика'
        context['topic'] = get_object_or_404(Topic, pk=self.topic)
        return context

    def get_initial(self):
        self.topic = self.kwargs['pk']
        initial = self.initial.copy()
        initial['topic'] = self.topic
        return initial

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(reverse('main:topic_sites', kwargs={'pk': self.topic}))


@method_decorator(user_passes_test(lambda u: u.is_staff), name='dispatch')
class TopicSiteDeleteView(DeleteView):
    model = TopicSite
    success_url = reverse_lazy('main:topics')  # TODO: Нужен переход на список сайтов выбранного топика

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'FNP: Удаление сайта топика'
        return context

mainapp/templates/mainapp/base.html
<!DOCTYPE html>

{% load static %}
{% load cache %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ page_title }}
        {% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <link rel="icon" type="image/gif" href="{% static 'img/small_logo.gif' %}" />
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
		<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>

<body>
    <div class="wrapper">
        <div class="top">
            {% block container %}
            {% endblock %}
        </div>
        <footer class="bottom">
            {% block footer %}
            <div class="container">
                <div class="footer padding-site">
                    <section class="copyright">
                        <div class="hidden">
                            <h2>Copyright</h2>
                        </div>
                        <div class="copy-col">
                           <p class="copyright-text">&copy;&nbsp;Copyright&nbsp;&mdash; FINNEWS 2020. All Rights Reserved.</p>
                        </div>
                        <div class="copy-col">
                           <a href="#" class="copyr-link"><i class="fab fa-facebook-f copyr-img"></i></a>
                           <a href="#" class="copyr-link"><i class="fab fa-twitter copyr-img"></i></a>
                           <a href="#" class="copyr-link"><i class="fab fa-pinterest-p copyr-img"></i></a>
                        </div>
                        <div class="copy-col">
                            <a href="#" class="terms-link">Terms &amp;&nbsp;Conditions</a>
                            &nbsp;/&nbsp;<a href="#" class="terms-link">Privacy policy &amp;&nbsp;Cookies</a>
                        </div>
                    </section>
                    <section>
                        <div class="hidden">
                            <h2>Referens</h2>
                        </div>
                        <p>
                            <a href="https://jigsaw.w3.org/css-validator/check/referer">
                            <img style="border:0;width:88px;height:31px" src="https://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Correct CSS!">
                            </a>
                        </p>
                    </section> 
                </div>
            </div>
            {% endblock %}
        </footer>
    </div>
</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load cache %}

{% block container %}
            <div class="container">
                <header class="padding-site">
                    {% include 'mainapp/inc/inc__main_menu.html' %}
                </header>
                <main>
                    <section class="">
                        <div class="">
                        </div>
                    </section>
                </main>
            </div>
            <div class="category-products clearfix container">
                <h3>Доступные финансовые сайты</h3>
                {% for site in sites %}
                    <button type="button" class="btn"><a href="{% url 'main:site' site.pk %}">{{ site.name }}</a></button>
                {% endfor %}
            </div>
{% endblock %}

mainapp/templates/mainapp/news.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load cache %}

{% block container %}
            <div class="container">
                <header class="padding-site">
                    {% include 'mainapp/inc/inc__main_menu.html' %}
                </header>
                <main>
                    <section class="">
                        <div class="">
                        </div>
                    </section>
                </main>
            </div>
            <div class="category-products clearfix container">
                <h3>Сайт "{{ site_name }}" (последние 20 новостей)</h3>
                {% for line in news %}
                <p><span>{{ line.news_date|date:"d.m.Y H:i" }}</span>  <a href="{{ line.ref }}">{{ line.brief_info }}</a></p>
                {% endfor %}
                <p>...</p>
            </div>
{% endblock %}

mainapp/templates/mainapp/topic_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block container %}
 	 <div class="container">
		<header class="padding-site">
			{% include 'mainapp/inc/inc__main_menu.html' %}
		</header>
	</div>
    <div class="category_delete">
        Уверены, что хотите удалить топик <b>{{ object.name }}</b>
                ?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'main:topics' %}" class="btn btn-success">отмена</a>
    </div>
{% endblock %}

mainapp/templates/mainapp/topic_form.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load cache %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>

        <a href="{% url 'main:topic_list' %}" class="btn btn-round form-control last">
            к списку
        </a>
    </div>

{% endblock %}

mainapp/templates/mainapp/topic_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load cache %}
<!--{% block title %}FNP: Список топиков{% endblock title %}-->

{% block container %}
	 <div class="container">
		<header class="padding-site">
			{% include 'mainapp/inc/inc__main_menu.html' %}
		</header>
	</div>
    <div class="categories_list container">
		<h3>Список топиков</h3>
        <button class="new_category">
			<a href="{% url 'main:topic_create' %}">новый</a>
		</button>

		{% for object in object_list %}
			<div class="category_record">
				<div class="category_name">
					{{ object.name|title }}
				</div>
				<div class="category_actions">
                    <button>
                        <a href="{% url 'main:topic_sites' object.pk %}">сайты топика</a>
                    </button>
                    <button>
                        <a href="{% url 'main:topic_update' object.pk %}">редактировать</a>
                    </button>
                    <button>
                        <a href="{% url 'main:topic_delete' object.pk %}">удалить</a>
                    </button>
				</div>
				<div class="category_desc">
					{{ object.keywords|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

mainapp/templates/mainapp/topicsite_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block container %}
 	 <div class="container">
		<header class="padding-site">
			{% include 'mainapp/inc/inc__main_menu.html' %}
		</header>
	</div>
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.site }}</b> из топика <b>{{ object.topic.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'main:topic_sites' object.topic.pk %}" class="btn btn-success">отмена</a>
    </div>
{% endblock %}

mainapp/templates/mainapp/topicsite_form.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block container %}
 	 <div class="container">
		<header class="padding-site">
			{% include 'mainapp/inc/inc__main_menu.html' %}
		</header>
	</div>
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'main:topic_sites' topic.pk %}" class="btn btn-round form-control last">
            к списку сайтов топика
        </a>
    </div>
{% endblock %}

mainapp/templates/mainapp/topicsite_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
 	 <div class="container">
		<header class="padding-site">
			{% include 'mainapp/inc/inc__main_menu.html' %}
		</header>
	</div>
    <div class="new_products_list container">
		<h3>Список сайтов топика <b>{{ topic.name }}</b></h3>
		<button class="new_product">
			<a href="{% url 'main:topicsite_create' topic.pk %}">новый</a>
		</button>
		
		{% for object in object_list %}
			<div class="product_record">
				<div class="product_name">
					{{ object|title }}
				</div>
				<div class="product_actions">
					<button>
						<a href="{% url 'main:topicsite_delete' object.pk %}">удалить</a>
					</button>
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}